# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_trunc_norm <- function(n, lb, ub, verbose = FALSE) {
    .Call('_HTLR_sample_trunc_norm', PACKAGE = 'HTLR', n, lb, ub, verbose)
}

sample_post_ichi <- function(n, sigmasq, alpha1, alpha0 = 1E-5, w0 = 1E-5, verbose = FALSE) {
    .Call('_HTLR_sample_post_ichi', PACKAGE = 'HTLR', n, sigmasq, alpha1, alpha0, w0, verbose)
}

sample_trunc_beta <- function(n, alpha, beta, lb = 0, ub = 1, verbose = FALSE) {
    .Call('_HTLR_sample_trunc_beta', PACKAGE = 'HTLR', n, alpha, beta, lb, ub, verbose)
}

htlr_fit_helper <- function(p, K, n, X, ymat, ybase, ptype, alpha, s, eta, iters_rmc, iters_h, thin, leap_L, leap_L_h, leap_step, hmc_sgmcut, deltas, sigmasbt, keep_warmup_hist, silence, legacy) {
    .Call('_HTLR_htlr_fit_helper', PACKAGE = 'HTLR', p, K, n, X, ymat, ybase, ptype, alpha, s, eta, iters_rmc, iters_h, thin, leap_L, leap_L_h, leap_step, hmc_sgmcut, deltas, sigmasbt, keep_warmup_hist, silence, legacy)
}

log_sum_exp <- function(A) {
    .Call('_HTLR_log_sum_exp', PACKAGE = 'HTLR', A)
}

spl_sgm_ig <- function(alpha, K, w, vardeltas) {
    .Call('_HTLR_spl_sgm_ig', PACKAGE = 'HTLR', alpha, K, w, vardeltas)
}

std_helper <- function(A) {
    .Call('_HTLR_std_helper', PACKAGE = 'HTLR', A)
}

comp_vardeltas <- function(deltas) {
    .Call('_HTLR_comp_vardeltas', PACKAGE = 'HTLR', deltas)
}

comp_lsl <- function(A) {
    .Call('_HTLR_comp_lsl', PACKAGE = 'HTLR', A)
}

log_normcons <- function(A) {
    .Call('_HTLR_log_normcons', PACKAGE = 'HTLR', A)
}

gendata_FAM_helper <- function(n, muj, muj_rep, A, sd_g, stdx) {
    .Call('_HTLR_gendata_FAM_helper', PACKAGE = 'HTLR', n, muj, muj_rep, A, sd_g, stdx)
}

